INSERT INTO book_links
  (group_name, name, url, image_url, premium)
VALUES
  ('aktivitas anak muslim', 'surga dan neraka', 'https://drive.google.com/file/d/1A1nxJQg_ZTEUrUfEu9R_HNZjKaXeddQd/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'surat surat pendek', 'https://drive.google.com/file/d/1dS3IgdaN4bTH-Jtm3Z5Wnp9dISY6yyUH/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'sifat sifat Allah', 'https://drive.google.com/file/d/1Aaifv6hd8rW0BI5fE44sS65sX4Ors7us/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'sholat dan wudhu', 'https://drive.google.com/file/d/1oXy2OfhXNJFcUuE0MqOCZ6EdF2y5BTB4/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'rukun iman dan islam', 'https://drive.google.com/file/d/19lvCWb-THnzWNLoCFoz7mbKdJo2FWl8c/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'puasa', 'https://drive.google.com/file/d/1pJI-uwpEFVaIyvfob3g36ANFopeKj1ej/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'perbuatan terpuji', 'https://drive.google.com/file/d/1zzDQEs0KXcmo6-vjPMWJzccODUffYsgW/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'nama malaikat', 'https://drive.google.com/file/d/1EISc-6XnBpzwS7EtdmAautIyONN_KpIK/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'macam macam najis', 'https://drive.google.com/file/d/1vX66S3NCWHbL3ofW8L_DA7bUR0-SnxzR/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'nabi dan rasul', 'https://drive.google.com/file/d/1VKKUI1BOd8CXgsXbnoYMhc1C5JLl33nB/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'mewarnai', 'https://drive.google.com/file/d/13V3iUnS1kKWNWcSlRMLICXjLqW-w0HaP/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'mengenal harakat', 'https://drive.google.com/file/d/1ESSGYLThFV_3SvHLodbKWRxGXQp1Lo2a/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'lain lain', 'https://drive.google.com/file/d/1U2HrIpJPvM0UWDPdCSSVjd4qP4dN1CyI/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'huruf hijaiyah', 'https://drive.google.com/file/d/1H8zNrkNqM9uPYdI503rNZ8d_QAFTDVl9/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'hari kiamat', 'https://drive.google.com/file/d/1tB5bUQrbNQu9x63KfyP2be_RXbFuQA3L/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'hari besar islam', 'https://drive.google.com/file/d/1CGQk0dg0FbMDlEYmKqnlbj4bkPGGsfEg/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'haji dan umrah', 'https://drive.google.com/file/d/1JWymeF4xaOnCL-7ScTdiFo_Nc8VqpGpA/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'worksheet anak muslim', 'https://drive.google.com/file/d/1ha6h7saHdTDkEYOwMboFAeVgON9-Sp_S/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'menulis huruf hijaiyah', 'https://drive.google.com/file/d/1FZZnF-cgfpAz-4a7MjO3RtaJhTZL1nab/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'kaligrafi', 'https://drive.google.com/file/d/1yiydJT2wj_Q81DQXScBKlx3K2WqfDvsP/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'huruf hijaiyah', 'https://drive.google.com/file/d/1tH4Xq8w3FMAiyhMfO_CiHVwAXSCprbmg/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', '99 asmaul husna', 'https://drive.google.com/file/d/1jWFbWh80daH4XawbHyMT4uHTV8AaCt8-/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'jurnal ramadhan', 'https://drive.google.com/file/d/1KXkkGHCaG_Og1d2K7ilHyOVH-mcHTyZG/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'aktivitas ramadhan', 'https://drive.google.com/file/d/1kVgcude8VAqH3wZhBTWEscSr3c1jD7Kv/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', '30 hari aktivitas mewarnai', 'https://drive.google.com/file/d/1txX8A1jF9iIVHw_wekXrFqUbIXd0dq_X/view?usp=drive_link', '', false),
  ('aktivitas anak muslim', 'angka dalam bahasa arab', 'https://drive.google.com/file/d/13-4zZ7RyHf1Pv2b8NgrS2cGxb_aKzOn2/view?usp=drive_link', '', false)
