INSERT INTO flash_cards
  (slug,name_id, name_en, picture_url, tags)
VALUES
  ('lime', 'lime', 'jeruk nipis', 'https://data.cabocil.com/assets/fruits/lime.png', '{"fruit"}'),
  ('papaya', 'papaya', 'pepaya', 'https://data.cabocil.com/assets/fruits/papaya.png', '{"fruit"}'),
  ('melon', 'melon', 'melon', 'https://data.cabocil.com/assets/fruits/melon.png', '{"fruit"}'),
  ('peach', 'peach', 'peach', 'https://data.cabocil.com/assets/fruits/peach.png', '{"fruit"}'),
  ('coconut', 'kelapa', 'coconut', 'https://data.cabocil.com/assets/fruits/coconut.png', '{"fruit"}'),
  ('guava', 'jambu biji', 'guava', 'https://data.cabocil.com/assets/fruits/guava.png', '{"fruit"}'),
  ('watermelon', 'watermelon', 'semangka', 'https://data.cabocil.com/assets/fruits/watermelon.png', '{"fruit"}'),
  ('kiwi', 'kiwi', 'kiwi', 'https://data.cabocil.com/assets/fruits/kiwi.png', '{"fruit"}'),
  ('starfruit', 'starfruit', 'belimbing', 'https://data.cabocil.com/assets/fruits/starfruit.png', '{"fruit"}'),
  ('rambutan', 'rambutan', 'rambutan', 'https://data.cabocil.com/assets/fruits/rambutan.png', '{"fruit"}'),
  ('pomegranate', 'pomegranate', 'pomegranate', 'https://data.cabocil.com/assets/fruits/pomegranate.png', '{"fruit"}'),
  ('banana', 'banana', 'pisang', 'https://data.cabocil.com/assets/fruits/banana.png', '{"fruit"}'),
  ('grape', 'grape', 'anggur', 'https://data.cabocil.com/assets/fruits/grape.png', '{"fruit"}'),
  ('blueberry', 'blueberry', 'blueberry', 'https://data.cabocil.com/assets/fruits/blueberry.png', '{"fruit"}'),
  ('blackberry', 'blackberry', 'blackberry', 'https://data.cabocil.com/assets/fruits/blackberry.png', '{"fruit"}'),
  ('orange', 'orange', 'jeruk', 'https://data.cabocil.com/assets/fruits/orange.png', '{"fruit"}'),
  ('manggo', 'manggo', 'mangga', 'https://data.cabocil.com/assets/fruits/manggo.png', '{"fruit"}'),
  ('lemon', 'lemon', 'lemon', 'https://data.cabocil.com/assets/fruits/lemon.png', '{"fruit"}'),
  ('durian', 'durian', 'durian', 'https://data.cabocil.com/assets/fruits/durian.png', '{"fruit"}'),
  ('strawberry', 'strawberry', 'strawberry', 'https://data.cabocil.com/assets/fruits/strawberry.png', '{"fruit"}'),
  ('avocado', 'avocado', 'alpukat', 'https://data.cabocil.com/assets/fruits/avocado.png', '{"fruit"}'),
  ('pineapple', 'pineapple', 'nanas', 'https://data.cabocil.com/assets/fruits/pineapple.png', '{"fruit"}'),
  ('apple', 'apple', 'apel', 'https://data.cabocil.com/assets/fruits/apple.png', '{"fruit"}'),
  ('date', 'date', 'kurma', 'https://data.cabocil.com/assets/fruits/date.png', '{"fruit"}'),
  ('plum', 'plum', 'plum', 'https://data.cabocil.com/assets/fruits/plum.png', '{"fruit"}'),
  ('raspberry', 'raspberry', 'raspberry', 'https://data.cabocil.com/assets/fruits/raspberry.png', '{"fruit"}'),
  ('pear', 'pear', 'pir', 'https://data.cabocil.com/assets/fruits/pear.png', '{"fruit"}'),
  ('lychee', 'lychee', 'leci', 'https://data.cabocil.com/assets/fruits/lychee.png', '{"fruit"}'),
  ('dragonfruit', 'dragonfruit', 'buah naga', 'https://data.cabocil.com/assets/fruits/dragonfruit.png', '{"fruit"}'),
  ('tomato', 'tomato', 'tomat', 'https://data.cabocil.com/assets/fruits/tomato.png', '{"fruit"}'),
  ('cherry', 'cherry', 'ceri', 'https://data.cabocil.com/assets/fruits/cherry.png', '{"fruit"}')
